In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tsfresh as tsf
import random
from torch.utils.data import random_split

df = pd.read_csv(r'C:\\Users\\Jiananyuan\Desktop\\QuickAccess\\DM_homework\dataset\\train.csv')
signals = df['heartbeat_signals'].str.split(',', expand=True)
signals.insert(0, '', df['label'], allow_duplicates=False)
col_names = ['label']
for i in range(0, 205):
    col_names.append('signal_' + str(i))
signals.columns = col_names
signals = pd.DataFrame(signals, dtype=np.float64)

def signal_enhance(_signal, sigma=0.1):
    scalingFactor = np.random.normal(loc=1.0, scale=sigma, size=(1, _signal.shape[1]))
    noise = np.matmul(np.ones((_signal.shape[0], 1)), scalingFactor)
    return _signal * noise

idx_set = signals.query('label==1').index
record_label_1 = signals.iloc[idx_set, :].reset_index(drop=True)
enhanced_signal_label_1 = record_label_1
for i in np.arange(16):
    tmp_enhanced_signal_label_1 = signal_enhance(record_label_1)
    enhanced_signal_label_1 = pd.concat((enhanced_signal_label_1, 
                                         tmp_enhanced_signal_label_1), axis=0).reset_index(drop=True)
enhanced_signal_label_1['label'] = 1

idx_set = signals.query('label==2').index
record_label_2 = signals.iloc[idx_set, :].reset_index(drop=True)
enhanced_signal_label_2 = record_label_2
for i in np.arange(3):
    tmp_enhanced_signal_label_2 = signal_enhance(record_label_2)
    enhanced_signal_label_2 = pd.concat((enhanced_signal_label_2, tmp_enhanced_signal_label_2), axis=0).reset_index(
        drop=True)
enhanced_signal_label_2['label'] = 2

idx_set = signals.query('label==3').index
record_label_3 = signals.iloc[idx_set, :].reset_index(drop=True)
enhanced_signal_label_3 = record_label_3
for i in np.arange(3):
    tmp_enhanced_signal_label_3 = signal_enhance(record_label_3)
    enhanced_signal_label_3 = pd.concat((enhanced_signal_label_3, tmp_enhanced_signal_label_3), axis=0).reset_index(
        drop=True)
enhanced_signal_label_3['label'] = 3

idx_set = signals.query('label==0').index
record_label_0 = signals.iloc[idx_set, :].reset_index(drop=True)

data_train = pd.concat([record_label_0, 
                        enhanced_signal_label_1, 
                        enhanced_signal_label_2, 
                        enhanced_signal_label_3], ignore_index=True)

def remove_last_zero(_series):
    nps = _series.to_numpy()
    zero_begin_idxs = np.arange(nps.shape[0])
    for i in np.arange(nps.shape[1])[::-1]:
        idxs = np.where(nps[zero_begin_idxs, i] <= 1.e-5)[0]
        if idxs.size > 0:
            nps[zero_begin_idxs[idxs], i] = np.nan
            zero_begin_idxs = zero_begin_idxs[idxs]
        else:
            break
    return pd.DataFrame(nps[:, :], index=_series.index, columns=_series.columns[:])

# data_train = remove_last_zero(data_train)

# drop_idx = list(data_train.index)
# drop_idx = random.sample(drop_idx, 3325)
# data_train = data_train.drop(drop_idx)


253325

In [53]:
from sklearn.utils import shuffle

data_train = shuffle(data_train)
net_train_data = data_train.iloc[:, 1:].to_numpy()
net_train_label = data_train.iloc[:, 0].to_numpy()

In [60]:
train_set = data_train.iloc[:200000, :]
test_set = data_train.iloc[200000:, :]

train_x = train_set.iloc[:, 1:].to_numpy()
train_y = train_set.iloc[:, 0].to_numpy()
valid_x = test_set.iloc[:, 1:].to_numpy()
valid_y = test_set.iloc[:, 0].to_numpy()

# train_data = data_train.iloc[:, 1:]
# train_label = data_train.iloc[:, 0]

# train_data = data_train.iloc[:, 1:].stack()
# train_data = train_data.reset_index()
# train_data.rename(columns={"level_0": "id", "level_1": "time", 0: "signals"}, 
#                   inplace=True)
# train_data["signals"] = train_data["signals"].astype(float)

# train_data

print(train_x.shape, train_y.shape, valid_x.shape, valid_y.shape)


(200000, 205) (200000,) (53325, 205) (53325,)


In [16]:
# train_label.values.tolist()
# net_train_data = train_data.values
# net_train_label = train_label.values
# net_train_data

array([[0.9912298 , 0.94353304, 0.7646773 , ...,        nan,        nan,
               nan],
       [0.9714822 , 0.92896875, 0.57293281, ...,        nan,        nan,
               nan],
       [0.97579528, 0.93408847, 0.65963666, ...,        nan,        nan,
               nan],
       ...,
       [0.88023307, 0.89468516, 0.89448266, ...,        nan,        nan,
               nan],
       [0.71712964, 0.68011328, 0.63003724, ...,        nan,        nan,
               nan],
       [0.84084461, 0.5637697 , 0.63639073, ...,        nan,        nan,
               nan]])

In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Sequential(
            nn.Conv1d(
                in_channels=1,
                out_channels=64,
                kernel_size=7,
                stride=1,
                padding=3,
            ),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.MaxPool1d(kernel_size=2)
        )
        
        self.conv2 = nn.Sequential(
            nn.Conv1d(64, 128, 5, 1, 2),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.MaxPool1d(2)
        )
        
        self.conv3 = nn.Sequential(
            nn.Conv1d(128, 256, 3, 1, 1), 
            nn.BatchNorm1d(256),
            nn.ReLU(), 
            nn.Conv1d(256, 256, 3, 1, 1),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.MaxPool1d(2)
        )
        
        self.fc1 = nn.Sequential(
            nn.Linear(6400, 4096),
            nn.BatchNorm1d(4096),
            nn.ReLU(),
        )
        
        self.fc2 = nn.Sequential(
            nn.Linear(4096, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
        )
        
        self.fc3 = nn.Linear(64, 4)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)

        x = x.view(x.size(0), -1)
#         print(x.size())
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        return x

In [25]:
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import copy

# 训练网络
def train_net(net, train_loader, valid_loader, EPOCH=20, LR=1e-5):
    # 交叉熵作为损失函数
    loss_fn = nn.CrossEntropyLoss()
    
    # Adam 优化器
    optimizer = torch.optim.Adam(net.parameters(), lr=LR)
    
    # 保留准确率最高的模型
    best_state = copy.deepcopy(net.state_dict())
    best_acc = 0

    for epoch in range(EPOCH):
        net.train()
        train_l = 0
        train_num = 0
        for b_x, b_y in train_loader:
            output = net(b_x)
            loss = loss_fn(output, b_y)
            optimizer.zero_grad() 
            loss.backward()
            optimizer.step()

            train_l += loss.cpu().item()
            train_num += len(b_x)
        
        net.eval()
        with torch.no_grad():
            valid_l = 0
            valid_num = 0
            right_num = 0.
            for b_x, b_y in valid_loader:
                output = net(b_x)
                loss = loss_fn(output, b_y)
                valid_l += loss.cpu().item()

                pred_y = torch.argmax(output, dim=1)
                valid_num += len(b_x)
                right_num += (pred_y == b_y).sum().item()
        valid_acc = right_num / valid_num
        if valid_acc >= best_acc:
            best_acc = valid_acc
            best_state = copy.deepcopy(net.state_dict())
        print('Epoch {} | train_loss {:.2e} | valid_loss {:.2e} | acc {:f} | best_acc {:f}'.format(epoch + 1, train_l / train_num, valid_l / valid_num, valid_acc, best_acc))
        
    
    return best_state


In [36]:
!pip3 install imblearn

In [57]:
from sklearn.model_selection import StratifiedKFold
from imblearn.over_sampling import RandomOverSampler
from torch.utils.data import TensorDataset
import time
net_states = []
seed = 2023

# 采用 10 折交叉验证，训练 10 个模型
sk = StratifiedKFold(n_splits=10, shuffle=True, random_state=seed)
for i, (train, valid) in enumerate(sk.split(net_train_data, net_train_label)):
    x_train = net_train_data[train]
    y_train = net_train_label[train]
    x_valid = net_train_data[valid]
    y_valid = net_train_label[valid]
    
    # # 对训练数据进行随机过采样
    x_train, y_train = RandomOverSampler(random_state=seed).fit_resample(x_train, y_train)

    x_train = torch.tensor(x_train, dtype=torch.float).unsqueeze(-2)
    x_valid = torch.tensor(x_valid, dtype=torch.float).unsqueeze(-2)
    y_train = torch.tensor(y_train, dtype=int)
    y_valid = torch.tensor(y_valid, dtype=int)
    
    # train_loader = DataLoader(TensorDataset(x_train, y_train), batch_size=512, shuffle=True, num_workers=2)
    # valid_loader = DataLoader(TensorDataset(x_valid, y_valid), batch_size=1024, shuffle=False)
    
    # print('\nTraining {}th net. {}\n'.format(i + 1, time.strftime('%H:%M:%S')))
    # net = Net()
    # s = train_net(net, train_loader, valid_loader, 30)
    # net_states.append(s)
    print(x_train.shape, y_train.shape, x_valid.shape, y_valid.shape)

# 保存模型参数
torch.save(net_states, 'net_state.pkl') 

torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25333, 1, 205]) torch.Size([25333])
torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25333, 1, 205]) torch.Size([25333])
torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25333, 1, 205]) torch.Size([25333])
torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25333, 1, 205]) torch.Size([25333])
torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25333, 1, 205]) torch.Size([25333])
torch.Size([257936, 1, 205]) torch.Size([257936]) torch.Size([25332, 1, 205]) torch.Size([25332])
torch.Size([257936, 1, 205]) torch.Size([257936]) torch.Size([25332, 1, 205]) torch.Size([25332])
torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25332, 1, 205]) torch.Size([25332])
torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25332, 1, 205]) torch.Size([25332])
torch.Size([257932, 1, 205]) torch.Size([257932]) torch.Size([25332, 1, 205]) torch.Size([25332])


In [61]:
seed = 2023

# x_train, x_label = RandomOverSampler(random_state=seed).fit_resample(x_train, x_label)

train_x = torch.tensor(train_x, dtype=torch.float).unsqueeze(-2)
valid_x = torch.tensor(valid_x, dtype=torch.float).unsqueeze(-2)
train_y = torch.tensor(train_y, dtype=int)
valid_y = torch.tensor(valid_y, dtype=int)
print(train_x.shape, train_y.shape, valid_x.shape, valid_y.shape)

train_loader = DataLoader(TensorDataset(train_x, train_y), batch_size=512, shuffle=True, num_workers=2)
valid_loader = DataLoader(TensorDataset(valid_x, valid_y), batch_size=1024, shuffle=False)

print('\nTraining {}th net. {}\n'.format(i + 1, time.strftime('%H:%M:%S')))
net = Net()
s = train_net(net, train_loader, valid_loader, 30)
torch.save(s, 'net_state.pkl')


torch.Size([200000, 1, 205]) torch.Size([200000]) torch.Size([53325, 1, 205]) torch.Size([53325])

Training 10th net. 13:22:00

Epoch 1 | train_loss 5.94e-04 | valid_loss 1.98e-04 | acc 0.986442 | best_acc 0.986442
Epoch 2 | train_loss 3.40e-04 | valid_loss 1.51e-04 | acc 0.992743 | best_acc 0.992743
Epoch 3 | train_loss 2.66e-04 | valid_loss 1.24e-04 | acc 0.994955 | best_acc 0.994955
Epoch 4 | train_loss 2.16e-04 | valid_loss 1.01e-04 | acc 0.995762 | best_acc 0.995762
Epoch 5 | train_loss 1.78e-04 | valid_loss 8.68e-05 | acc 0.996643 | best_acc 0.996643
Epoch 6 | train_loss 1.48e-04 | valid_loss 7.30e-05 | acc 0.996981 | best_acc 0.996981
Epoch 7 | train_loss 1.25e-04 | valid_loss 6.13e-05 | acc 0.997506 | best_acc 0.997506
Epoch 8 | train_loss 1.05e-04 | valid_loss 5.36e-05 | acc 0.997543 | best_acc 0.997543
Epoch 9 | train_loss 8.92e-05 | valid_loss 4.48e-05 | acc 0.997731 | best_acc 0.997731
Epoch 10 | train_loss 7.57e-05 | valid_loss 4.01e-05 | acc 0.997900 | best_acc 0.997900
E

In [70]:
# ****************** 以下生成 submit.csv 结果文件 ******************
df = pd.read_csv(r'C:\\Users\\Jiananyuan\Desktop\\QuickAccess\\DM_homework\dataset\\testA.csv')
test_signals = df['heartbeat_signals'].str.split(',', expand=True)
col_names = []
for i in range(0, 205):
    col_names.append('signal_' + str(i))
test_signals.columns = col_names
test_signals = pd.DataFrame(test_signals, dtype=np.float64)
# test_signals  =remove_last_zero(test_signals)

test_signals = torch.tensor(test_signals.to_numpy(), dtype=torch.float).unsqueeze(-2)
test_signals

tensor([[[0.9916, 1.0000, 0.6318,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.6076, 0.5417, 0.3407,  ..., 0.3506, 0.3506, 0.3639]],

        [[0.9753, 0.6711, 0.6868,  ..., 0.0000, 0.0000, 0.0000]],

        ...,

        [[0.9517, 0.9163, 0.6675,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.9277, 0.6772, 0.2429,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.6653, 0.5271, 0.5167,  ..., 0.0000, 0.0000, 0.0000]]])

In [71]:
net = Net()
test_pred = []

# 读入模型参数
net.load_state_dict(torch.load('net_state.pkl'))
net.eval()
with torch.no_grad():
    cur_pred = []
    for i in range(100):
        b_x = test_signals[i * 200: (i + 1) * 200]
        output = nn.functional.softmax(net(b_x), dim=1).numpy().tolist()
        cur_pred.extend(output)
test_pred.append(cur_pred)

# test_pred = np.array(test_pred)
# test_avg = test_pred.mean(axis=0)
# test_y_pred = test_avg.argmax(axis=1)
# test_y_pred

array([0, 2, 3, ..., 2, 0, 3], dtype=int64)

AttributeError: 'list' object has no attribute 'mean'

In [72]:
test_pred

array([[[9.98525560e-01, 4.95368207e-04, 6.36133074e-04, 3.42902378e-04],
        [2.23498605e-03, 3.06179048e-03, 9.93577719e-01, 1.12543185e-03],
        [1.71101186e-03, 1.09001505e-03, 1.25909201e-03, 9.95939851e-01],
        ...,
        [8.27118475e-03, 3.87121947e-03, 9.86034751e-01, 1.82286615e-03],
        [9.97383177e-01, 9.04604851e-04, 1.07321993e-03, 6.39071281e-04],
        [3.64486307e-01, 3.80276069e-02, 1.14602380e-01, 4.82883692e-01]]])

In [73]:
test_avg

array([[9.98525560e-01, 4.95368207e-04, 6.36133074e-04, 3.42902378e-04],
       [2.23498605e-03, 3.06179048e-03, 9.93577719e-01, 1.12543185e-03],
       [1.71101186e-03, 1.09001505e-03, 1.25909201e-03, 9.95939851e-01],
       ...,
       [8.27118475e-03, 3.87121947e-03, 9.86034751e-01, 1.82286615e-03],
       [9.97383177e-01, 9.04604851e-04, 1.07321993e-03, 6.39071281e-04],
       [3.64486307e-01, 3.80276069e-02, 1.14602380e-01, 4.82883692e-01]])

In [78]:
pred = pd.DataFrame(test_avg)
pred

0         1         2         3
0      0.998526  0.000495  0.000636  0.000343
1      0.002235  0.003062  0.993578  0.001125
2      0.001711  0.001090  0.001259  0.995940
3      0.998115  0.000588  0.000741  0.000556
4      0.997998  0.000678  0.000729  0.000595
...         ...       ...       ...       ...
19995  0.997335  0.000738  0.000852  0.001075
19996  0.996882  0.001026  0.001194  0.000899
19997  0.008271  0.003871  0.986035  0.001823
19998  0.997383  0.000905  0.001073  0.000639
19999  0.364486  0.038028  0.114602  0.482884

[20000 rows x 4 columns]

In [79]:
result=pd.read_csv(r'C:\\Users\\Jiananyuan\\Desktop\\QuickAccess\\DM_homework\\dataset\\sample_submit.csv')
result['label_0']=pred[0]
result['label_1']=pred[1]
result['label_2']=pred[2]
result['label_3']=pred[3]
result.to_csv('submit.csv',index=False)
result

id   label_0   label_1   label_2   label_3
0      100000  0.998526  0.000495  0.000636  0.000343
1      100001  0.002235  0.003062  0.993578  0.001125
2      100002  0.001711  0.001090  0.001259  0.995940
3      100003  0.998115  0.000588  0.000741  0.000556
4      100004  0.997998  0.000678  0.000729  0.000595
...       ...       ...       ...       ...       ...
19995  119995  0.997335  0.000738  0.000852  0.001075
19996  119996  0.996882  0.001026  0.001194  0.000899
19997  119997  0.008271  0.003871  0.986035  0.001823
19998  119998  0.997383  0.000905  0.001073  0.000639
19999  119999  0.364486  0.038028  0.114602  0.482884

[20000 rows x 5 columns]